spring:
  profiles:
    active: real
    include: oauth,real-db
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  session:
    store-type: jdbc